title: '[Timing] Principles of External Signal Ingress for DMF Media Workloads'
short_description: '[Timing] Principles of External Signal Ingress for DMF Media Workloads'
initial_maintainers:
- peterbrightwell
